export const OUTBOUND_COMMAND_ENVELOPE_VERSION = 'max-outbound-command-v1' as const
export const MAX_PER_CHAT_OUTBOUND_ACTOR_ENABLED = 'MAX_PER_CHAT_OUTBOUND_ACTOR_ENABLED' as const
export const MAX_OUTBOUND_TEXT_BYTES = 65_536
export const MAX_OUTBOUND_PAGE_LIMIT = 100
export const DEFAULT_ACTOR_LEASE_MILLISECONDS = 30_000
export const DEFAULT_RESERVATION_LEASE_MILLISECONDS = 15_000
