/**
 * WhatsApp session cleanup — reclaims state from zombie puppeteer sessions.
 *
 * Problem: when CRM exits uncleanly (taskkill, power loss, Windows sleep,
 * uncaught exception), puppeteer-controlled Chrome processes may remain
 * alive holding file locks on .wwebjs_auth/session-<id>. Next startup then
 * fails with:
 *    Error: The browser is already running for <userDataDir>.
 *    Use a different `userDataDir` or stop the running browser first.
 *
 * This module is called on startup BEFORE initializing any WA client,
 * and can also be invoked from the watchdog hard-restart path.
 */

import { execFile } from 'child_process'
import { promisify } from 'util'
import * as fs from 'fs/promises'
import * as path from 'path'

const execFileAsync = promisify(execFile)

const WWEBJS_AUTH_DIR = path.join(process.cwd(), 'node_modules', '.wwebjs_auth')

// Chrome leaves these in the user profile when it runs; holding them
// indicates "another browser is using this profile". We remove them
// after the holding process is killed.
const LOCK_FILES = ['SingletonLock', 'SingletonCookie', 'SingletonSocket', 'lockfile']

/**
 * Kill zombie Chrome processes belonging to wa-web.js puppeteer sessions.
 * Identified by --user-data-dir= pointing inside .wwebjs_auth.
 * Safe: does NOT touch the user's personal Chrome browser.
 * Windows-only (no-op on other platforms — Linux/macOS don't have this issue).
 */
async function killZombieWhatsAppChromes(): Promise<number> {
    if (process.platform !== 'win32') return 0

    let pids: number[] = []
    try {
        // Use PowerShell CIM — more reliable than tasklist on modern Windows,
        // doesn't need interactive elevation.
        // execFile avoids quoting hell: each arg is passed literally, no need
        // to escape nested quotes around the filter value.
        const psCommand =
            `Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" | ` +
            `Where-Object { $_.CommandLine -match '\\.wwebjs_auth' } | ` +
            `Select-Object -ExpandProperty ProcessId`

        const { stdout } = await execFileAsync(
            'powershell',
            ['-NoProfile', '-NonInteractive', '-Command', psCommand],
            { timeout: 15_000, windowsHide: true }
        )

        pids = stdout
            .split(/\r?\n/)
            .map(s => s.trim())
            .filter(s => s.length > 0)
            .map(s => parseInt(s, 10))
            .filter(n => Number.isFinite(n) && n > 0)
    } catch (err: any) {
        // Don't block startup if query fails — just log and continue.
        console.warn(`[WA-CLEANUP] Failed to list chrome processes: ${err.message}`)
        return 0
    }

    if (pids.length === 0) return 0

    let killed = 0
    for (const pid of pids) {
        try {
            // On Windows, process.kill with any signal calls TerminateProcess.
            // Works without admin rights if we started the process (we did — puppeteer).
            process.kill(pid, 'SIGTERM')
            killed++
        } catch (err: any) {
            // ESRCH = already dead. EPERM = we didn't launch it (someone else's chrome).
            if (err.code !== 'ESRCH') {
                console.warn(`[WA-CLEANUP] Failed to kill pid ${pid}: ${err.message}`)
            }
        }
    }

    if (killed > 0) {
        console.log(`[WA-CLEANUP] Killed ${killed} zombie chrome processes (of ${pids.length} candidates)`)
    }
    return killed
}

/**
 * Remove stale SingletonLock/etc files from session-* folders.
 * Safe: these files are regenerated by Chrome on next launch.
 *
 * @param sessionId — if provided, only clean that session's locks (used by watchdog hard-restart)
 */
async function removeSessionLocks(sessionId?: string): Promise<number> {
    let sessionDirs: string[]
    try {
        const entries = await fs.readdir(WWEBJS_AUTH_DIR, { withFileTypes: true })
        sessionDirs = entries
            .filter(e => e.isDirectory() && e.name.startsWith('session-'))
            .map(e => path.join(WWEBJS_AUTH_DIR, e.name))
    } catch {
        // .wwebjs_auth doesn't exist yet — nothing to clean.
        return 0
    }

    if (sessionId) {
        const target = path.join(WWEBJS_AUTH_DIR, `session-${sessionId}`)
        sessionDirs = sessionDirs.filter(d => d === target)
    }

    let removed = 0
    for (const sessionDir of sessionDirs) {
        for (const lockFile of LOCK_FILES) {
            const fullPath = path.join(sessionDir, lockFile)
            try {
                await fs.unlink(fullPath)
                removed++
            } catch {
                // File doesn't exist — normal case, not an error.
            }
        }

        // Chrome also keeps lock files inside Default/ subdirectory sometimes.
        const defaultDir = path.join(sessionDir, 'Default')
        for (const lockFile of LOCK_FILES) {
            const fullPath = path.join(defaultDir, lockFile)
            try {
                await fs.unlink(fullPath)
                removed++
            } catch {
                // ignore
            }
        }
    }

    if (removed > 0) {
        console.log(`[WA-CLEANUP] Removed ${removed} stale lock files${sessionId ? ` (session ${sessionId})` : ''}`)
    }
    return removed
}

/**
 * Full cleanup: kill zombie chromes + remove stale locks.
 * Call on startup before warmup, or before hard-restart from watchdog.
 *
 * @param sessionId — if provided, narrow to one session (watchdog case)
 */
export async function cleanupStaleWhatsAppSessions(
    sessionId?: string
): Promise<{ killedChromeCount: number; removedLockCount: number }> {
    // Step 1: kill zombie puppeteer chromes.
    // When running per-session (watchdog), still do global kill — the zombie
    // may be from any session and we can't trivially distinguish.
    const killedChromeCount = await killZombieWhatsAppChromes()

    // Step 2: brief pause so Windows releases file handles. Empirically 1s
    // is enough; 1.5s is defensive.
    if (killedChromeCount > 0) {
        await new Promise(resolve => setTimeout(resolve, 1500))
    }

    // Step 3: remove stale locks.
    const removedLockCount = await removeSessionLocks(sessionId)

    return { killedChromeCount, removedLockCount }
}
