export const DISMISS_BOT_LINK_REQUEST_COMMAND_V1='telegram_channel.DismissBotLinkRequestCommand.v1' as const
export const DISMISS_BOT_LINK_REQUEST_RESULT_V1='telegram_channel.DismissBotLinkRequestResult.v1' as const
export const RECORD_PENDING_BOT_LINK_REQUEST_COMMAND_V1='telegram_channel.RecordPendingBotLinkRequestCommand.v1' as const
export const RECORD_PENDING_BOT_LINK_REQUEST_RESULT_V1='telegram_channel.RecordPendingBotLinkRequestResult.v1' as const
export interface DismissBotLinkRequestCommandV1{contract:typeof DISMISS_BOT_LINK_REQUEST_COMMAND_V1;requestId:string}
export interface DismissBotLinkRequestResultV1{contract:typeof DISMISS_BOT_LINK_REQUEST_RESULT_V1;deleted:true}
export interface RecordPendingBotLinkRequestCommandV1{contract:typeof RECORD_PENDING_BOT_LINK_REQUEST_COMMAND_V1;telegramId:string;text:string}
export interface RecordPendingBotLinkRequestResultV1{contract:typeof RECORD_PENDING_BOT_LINK_REQUEST_RESULT_V1;recorded:true}
export class BotChatMessageCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:BotChatMessageCommandValidationError['code'],message:string){super(message);this.name='BotChatMessageCommandValidationError';this.code=code}}
const isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);function invalid(m:string):never{throw new BotChatMessageCommandValidationError('INVALID_CONTRACT',m)}function envelope(input:unknown,expected:string,prefix:string,fields:string[]):Record<string,unknown>{if(!isRecord(input))invalid('command must be an object');const extra=Object.keys(input).filter(k=>!fields.includes(k));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new BotChatMessageCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}
export function parseDismissBotLinkRequestCommandV1(input:unknown):DismissBotLinkRequestCommandV1{const v=envelope(input,DISMISS_BOT_LINK_REQUEST_COMMAND_V1,'telegram_channel.DismissBotLinkRequestCommand.',['contract','requestId']);if(typeof v.requestId!=='string')invalid('requestId must be a string');return v as unknown as DismissBotLinkRequestCommandV1}
export function parseRecordPendingBotLinkRequestCommandV1(input:unknown):RecordPendingBotLinkRequestCommandV1{const v=envelope(input,RECORD_PENDING_BOT_LINK_REQUEST_COMMAND_V1,'telegram_channel.RecordPendingBotLinkRequestCommand.',['contract','telegramId','text']);if(typeof v.telegramId!=='string')invalid('telegramId must be a string');if(typeof v.text!=='string')invalid('text must be a string');return v as unknown as RecordPendingBotLinkRequestCommandV1}
