export const REPLACE_DRIVER_TELEGRAM_LINK_COMMAND_V1='telegram_channel.ReplaceDriverTelegramLinkCommand.v1' as const
export const REPLACE_DRIVER_TELEGRAM_LINK_RESULT_V1='telegram_channel.ReplaceDriverTelegramLinkResult.v1' as const
export const DELETE_DRIVER_TELEGRAM_LINK_COMMAND_V1='telegram_channel.DeleteDriverTelegramLinkCommand.v1' as const
export const DELETE_DRIVER_TELEGRAM_LINK_RESULT_V1='telegram_channel.DeleteDriverTelegramLinkResult.v1' as const
export const PATCH_DRIVER_TELEGRAM_LINK_COMMAND_V1='telegram_channel.PatchDriverTelegramLinkCommand.v1' as const
export const PATCH_DRIVER_TELEGRAM_LINK_RESULT_V1='telegram_channel.PatchDriverTelegramLinkResult.v1' as const
export const UPSERT_DRIVER_TELEGRAM_LINK_COMMAND_V1='telegram_channel.UpsertDriverTelegramLinkCommand.v1' as const
export const UPSERT_DRIVER_TELEGRAM_LINK_RESULT_V1='telegram_channel.UpsertDriverTelegramLinkResult.v1' as const
export interface ReplaceDriverTelegramLinkCommandV1{contract:typeof REPLACE_DRIVER_TELEGRAM_LINK_COMMAND_V1;driverId:string;telegramId:bigint}
export interface ReplaceDriverTelegramLinkResultV1{contract:typeof REPLACE_DRIVER_TELEGRAM_LINK_RESULT_V1;replaced:true}
export interface DeleteDriverTelegramLinkCommandV1{contract:typeof DELETE_DRIVER_TELEGRAM_LINK_COMMAND_V1;telegramId:bigint}
export interface DeleteDriverTelegramLinkResultV1{contract:typeof DELETE_DRIVER_TELEGRAM_LINK_RESULT_V1;deleted:true}
export interface DriverTelegramLinkPatchV1{carLabel?:string|null;activeParkId?:string|null;carId?:string|null}
export interface PatchDriverTelegramLinkCommandV1{contract:typeof PATCH_DRIVER_TELEGRAM_LINK_COMMAND_V1;mappingId:string;patch:DriverTelegramLinkPatchV1}
export interface PatchDriverTelegramLinkResultV1{contract:typeof PATCH_DRIVER_TELEGRAM_LINK_RESULT_V1;updated:true}
export interface UpsertDriverTelegramLinkCommandV1{contract:typeof UPSERT_DRIVER_TELEGRAM_LINK_COMMAND_V1;driverId:string;telegramId:bigint;username:string|null;activeParkId:string}
export interface UpsertDriverTelegramLinkResultV1{contract:typeof UPSERT_DRIVER_TELEGRAM_LINK_RESULT_V1;upserted:true}
export class DriverTelegramCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:DriverTelegramCommandValidationError['code'],message:string){super(message);this.name='DriverTelegramCommandValidationError';this.code=code}}
const isRecord=(value:unknown):value is Record<string,unknown>=>typeof value==='object'&&value!==null&&!Array.isArray(value)
function invalid(message:string):never{throw new DriverTelegramCommandValidationError('INVALID_CONTRACT',message)}
function envelope(input:unknown,expected:string,prefix:string,fields:string[]):Record<string,unknown>{if(!isRecord(input))invalid('command must be an object');const extra=Object.keys(input).filter(key=>!fields.includes(key));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new DriverTelegramCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}
function string(value:unknown,key:string):void{if(typeof value!=='string'||value.trim()==='')invalid(`${key} is required`)}
function telegramId(value:unknown):void{if(typeof value!=='bigint')invalid('telegramId must be a bigint')}
export function parseReplaceDriverTelegramLinkCommandV1(input:unknown):ReplaceDriverTelegramLinkCommandV1{const value=envelope(input,REPLACE_DRIVER_TELEGRAM_LINK_COMMAND_V1,'telegram_channel.ReplaceDriverTelegramLinkCommand.',['contract','driverId','telegramId']);string(value.driverId,'driverId');telegramId(value.telegramId);return value as unknown as ReplaceDriverTelegramLinkCommandV1}
export function parseDeleteDriverTelegramLinkCommandV1(input:unknown):DeleteDriverTelegramLinkCommandV1{const value=envelope(input,DELETE_DRIVER_TELEGRAM_LINK_COMMAND_V1,'telegram_channel.DeleteDriverTelegramLinkCommand.',['contract','telegramId']);telegramId(value.telegramId);return value as unknown as DeleteDriverTelegramLinkCommandV1}
export function parsePatchDriverTelegramLinkCommandV1(input:unknown):PatchDriverTelegramLinkCommandV1{const value=envelope(input,PATCH_DRIVER_TELEGRAM_LINK_COMMAND_V1,'telegram_channel.PatchDriverTelegramLinkCommand.',['contract','mappingId','patch']);string(value.mappingId,'mappingId');if(!isRecord(value.patch))invalid('patch must be an object');const fields=['carLabel','activeParkId','carId'];const extra=Object.keys(value.patch).filter(key=>!fields.includes(key));if(extra.length)invalid(`unsupported patch field(s): ${extra.sort().join(', ')}`);if(Object.keys(value.patch).length===0)invalid('patch must not be empty');for(const key of fields){const candidate=value.patch[key];if(candidate!==undefined&&candidate!==null&&typeof candidate!=='string')invalid(`patch.${key} must be a string or null`)}return value as unknown as PatchDriverTelegramLinkCommandV1}
export function parseUpsertDriverTelegramLinkCommandV1(input:unknown):UpsertDriverTelegramLinkCommandV1{const value=envelope(input,UPSERT_DRIVER_TELEGRAM_LINK_COMMAND_V1,'telegram_channel.UpsertDriverTelegramLinkCommand.',['contract','driverId','telegramId','username','activeParkId']);string(value.driverId,'driverId');telegramId(value.telegramId);if(value.username!==null&&typeof value.username!=='string')invalid('username must be a string or null');string(value.activeParkId,'activeParkId');return value as unknown as UpsertDriverTelegramLinkCommandV1}
