/* eslint-disable @typescript-eslint/no-explicit-any -- Prisma client types
   for AiCallProject / AiCallScenario / AiCallMessage are generated by
   `prisma generate`. Until the dev runs that command, the types may not be
   available, so we go through `prisma as any` and unknown row shapes. */

/**
 * DB helpers for AI-call scenarios and their parent projects.
 *
 * Projects (AiCallProject) group scenarios by business purpose — lead
 * qualification, churn winback, NPS survey. Each scenario belongs to at most
 * one project; existing scenarios without a project on first list are
 * auto-backfilled to "Квалификация лида" (proj_lead_qual, seeded by migration
 * 20260517000000_add_ai_call_projects).
 *
 * On first read in a fresh database, auto-seeds the default scenario so the
 * settings page never shows an empty list.
 */

import { prisma } from '@/lib/prisma'
import type {
    AiCallGreetingVariant,
    AiCallOutcomeSchema,
    AiCallScenarioConfig,
    AiCallScenarioQuestion,
} from './types'
import {
    DEFAULT_SCENARIO_NAME,
    DEFAULT_SCENARIO_DESCRIPTION,
    DEFAULT_SCENARIO_SYSTEM_PROMPT,
    DEFAULT_SCENARIO_QUESTIONS,
    DEFAULT_SCENARIO_TARGET_SEC,
    DEFAULT_SCENARIO_OUTCOME_SCHEMA,
    DEFAULT_SCENARIO_GREETING_VARIANTS,
} from './default-scenario'

// Prisma types for AiCallScenario/AiCallProject are generated after
// `prisma generate`. Cast to `any` so this file compiles before the user
// runs migrations locally — same pattern as aiCallAnalysis/config.ts.
const db = prisma as any

// Fixed ID for the default project (matches migration seed)
export const DEFAULT_PROJECT_ID = 'proj_lead_qual'

export interface AiCallProjectConfig {
    id: string
    name: string
    slug: string
    description?: string
    sortOrder: number
}

export interface AiCallScenarioWithProject extends AiCallScenarioConfig {
    projectId: string | null
    projectName: string | null
}

function rowToConfig(row: any): AiCallScenarioWithProject {
    return {
        id: row.id,
        name: row.name,
        description: row.description ?? undefined,
        systemPrompt: row.systemPrompt,
        questions: (row.questions as AiCallScenarioQuestion[]) ?? [],
        targetDurationSec: row.targetDurationSec ?? undefined,
        // outcomeSchema is opaque JSON in Prisma. PR #57: scenarios that
        // opted-in get canonical-key validation at finalize-time + LLM
        // tool constraints at runtime. NULL = legacy passthrough.
        outcomeSchema: (row.outcomeSchema as AiCallOutcomeSchema | null) ?? undefined,
        // greetingVariants is opaque JSON in Prisma. PR #62: scenarios
        // that opted-in get A/B variant assignment at call start. NULL
        // = legacy LLM-generated greeting.
        greetingVariants: (row.greetingVariants as AiCallGreetingVariant[] | null) ?? undefined,
        projectId: row.projectId ?? null,
        projectName: row.project?.name ?? null,
    }
}

export async function listProjects(opts?: { includeInactive?: boolean }): Promise<AiCallProjectConfig[]> {
    const rows = await db.aiCallProject.findMany({
        where: opts?.includeInactive ? undefined : { isActive: true },
        orderBy: [{ sortOrder: 'asc' }, { createdAt: 'asc' }],
    })
    return rows.map((r: any) => ({
        id: r.id,
        name: r.name,
        slug: r.slug,
        description: r.description ?? undefined,
        sortOrder: r.sortOrder,
    }))
}

export async function getProject(id: string): Promise<AiCallProjectConfig | null> {
    const r = await db.aiCallProject.findUnique({ where: { id } })
    if (!r) return null
    return { id: r.id, name: r.name, slug: r.slug, description: r.description ?? undefined, sortOrder: r.sortOrder }
}

export async function listScenarios(opts?: { includeInactive?: boolean; projectId?: string }): Promise<AiCallScenarioWithProject[]> {
    const where: Record<string, unknown> = {}
    if (!opts?.includeInactive) where.isActive = true
    if (opts?.projectId) where.projectId = opts.projectId

    let rows = await db.aiCallScenario.findMany({
        where,
        orderBy: [{ projectId: 'asc' }, { createdAt: 'asc' }],
        include: { project: { select: { name: true } } },
    })

    // Backfill orphan scenarios (pre-project schema) into the default project.
    const orphans = rows.filter((r: any) => r.projectId == null)
    if (orphans.length > 0) {
        await db.aiCallScenario.updateMany({
            where: { id: { in: orphans.map((r: any) => r.id) } },
            data: { projectId: DEFAULT_PROJECT_ID },
        })
        // Re-read after backfill to include project name
        rows = await db.aiCallScenario.findMany({
            where,
            orderBy: [{ projectId: 'asc' }, { createdAt: 'asc' }],
            include: { project: { select: { name: true } } },
        })
    }

    if (rows.length === 0 && !opts?.projectId) {
        // Auto-seed default scenario into the default project.
        const seeded = await createScenario({
            name: DEFAULT_SCENARIO_NAME,
            description: DEFAULT_SCENARIO_DESCRIPTION,
            systemPrompt: DEFAULT_SCENARIO_SYSTEM_PROMPT,
            questions: DEFAULT_SCENARIO_QUESTIONS,
            targetDurationSec: DEFAULT_SCENARIO_TARGET_SEC,
            outcomeSchema: DEFAULT_SCENARIO_OUTCOME_SCHEMA,
            greetingVariants: DEFAULT_SCENARIO_GREETING_VARIANTS,
            projectId: DEFAULT_PROJECT_ID,
        })
        return [seeded]
    }
    return rows.map(rowToConfig)
}

export async function getScenario(id: string): Promise<AiCallScenarioWithProject | null> {
    const row = await db.aiCallScenario.findUnique({
        where: { id },
        include: { project: { select: { name: true } } },
    })
    return row ? rowToConfig(row) : null
}

export async function createScenario(input: {
    name: string
    description?: string
    systemPrompt: string
    questions: AiCallScenarioQuestion[]
    targetDurationSec?: number
    outcomeSchema?: AiCallOutcomeSchema
    greetingVariants?: AiCallGreetingVariant[]
    projectId?: string
}): Promise<AiCallScenarioWithProject> {
    const row = await db.aiCallScenario.create({
        data: {
            name: input.name,
            description: input.description,
            systemPrompt: input.systemPrompt,
            questions: input.questions as any,
            targetDurationSec: input.targetDurationSec,
            outcomeSchema: input.outcomeSchema as any,
            greetingVariants: input.greetingVariants as any,
            projectId: input.projectId ?? DEFAULT_PROJECT_ID,
            isActive: true,
        },
        include: { project: { select: { name: true } } },
    })
    return rowToConfig(row)
}

export async function updateScenario(
    id: string,
    patch: {
        name?: string
        description?: string
        systemPrompt?: string
        questions?: AiCallScenarioQuestion[]
        targetDurationSec?: number
        outcomeSchema?: AiCallOutcomeSchema | null
        greetingVariants?: AiCallGreetingVariant[] | null
        isActive?: boolean
        projectId?: string
    },
): Promise<AiCallScenarioWithProject> {
    const row = await db.aiCallScenario.update({
        where: { id },
        data: {
            ...(patch.name !== undefined && { name: patch.name }),
            ...(patch.description !== undefined && { description: patch.description }),
            ...(patch.systemPrompt !== undefined && { systemPrompt: patch.systemPrompt }),
            ...(patch.questions !== undefined && { questions: patch.questions as any }),
            ...(patch.targetDurationSec !== undefined && { targetDurationSec: patch.targetDurationSec }),
            ...(patch.outcomeSchema !== undefined && { outcomeSchema: patch.outcomeSchema as any }),
            ...(patch.greetingVariants !== undefined && { greetingVariants: patch.greetingVariants as any }),
            ...(patch.isActive !== undefined && { isActive: patch.isActive }),
            ...(patch.projectId !== undefined && { projectId: patch.projectId }),
        },
        include: { project: { select: { name: true } } },
    })
    return rowToConfig(row)
}

export async function deleteScenario(id: string): Promise<void> {
    // Soft delete — keep history for any past AI calls that reference it
    await db.aiCallScenario.update({
        where: { id },
        data: { isActive: false },
    })
}
