export const CREATE_AI_AGENT_PROFILE_COMMAND_V1='calling.CreateAiAgentProfileCommand.v1' as const
export const CREATE_AI_AGENT_PROFILE_RESULT_V1='calling.CreateAiAgentProfileResult.v1' as const
export const UPDATE_AI_AGENT_PROFILE_COMMAND_V1='calling.UpdateAiAgentProfileCommand.v1' as const
export const UPDATE_AI_AGENT_PROFILE_RESULT_V1='calling.UpdateAiAgentProfileResult.v1' as const
export const DELETE_AI_AGENT_PROFILE_COMMAND_V1='calling.DeleteAiAgentProfileCommand.v1' as const
export const DELETE_AI_AGENT_PROFILE_RESULT_V1='calling.DeleteAiAgentProfileResult.v1' as const
export interface AiAgentProfileV1{id:string;name:string;description:string|null;promptRole:string|null;promptTone:string|null;promptAllowed:string|null;promptForbidden:string|null;isDefault:boolean;sortOrder:number;createdAt:Date;updatedAt:Date}
export interface CreateAiAgentProfileInputV1{name:string;description:string|null;promptRole:string|null;promptTone:string|null;promptAllowed:string|null;promptForbidden:string|null}
export interface AiAgentProfilePatchV1{name?:string;description?:string|null;promptRole?:string|null;promptTone?:string|null;promptAllowed?:string|null;promptForbidden?:string|null}
export interface CreateAiAgentProfileCommandV1{contract:typeof CREATE_AI_AGENT_PROFILE_COMMAND_V1;profile:CreateAiAgentProfileInputV1}
export interface CreateAiAgentProfileResultV1{contract:typeof CREATE_AI_AGENT_PROFILE_RESULT_V1;profile:AiAgentProfileV1}
export interface UpdateAiAgentProfileCommandV1{contract:typeof UPDATE_AI_AGENT_PROFILE_COMMAND_V1;profileId:string;patch:AiAgentProfilePatchV1}
export interface UpdateAiAgentProfileResultV1{contract:typeof UPDATE_AI_AGENT_PROFILE_RESULT_V1;profile:AiAgentProfileV1}
export interface DeleteAiAgentProfileCommandV1{contract:typeof DELETE_AI_AGENT_PROFILE_COMMAND_V1;profileId:string}
export interface DeleteAiAgentProfileResultV1{contract:typeof DELETE_AI_AGENT_PROFILE_RESULT_V1;deleted:true}
export class AiAgentProfileCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:AiAgentProfileCommandValidationError['code'],message:string){super(message);this.name='AiAgentProfileCommandValidationError';this.code=code}}
const PROFILE_FIELDS=['name','description','promptRole','promptTone','promptAllowed','promptForbidden'],isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);function invalid(m:string):never{throw new AiAgentProfileCommandValidationError('INVALID_CONTRACT',m)}function envelope(input:unknown,expected:string,prefix:string,fields:string[]):Record<string,unknown>{if(!isRecord(input))invalid('command must be an object');const extra=Object.keys(input).filter(k=>!fields.includes(k));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new AiAgentProfileCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}function profileValues(input:unknown,partial:boolean):Record<string,unknown>{if(!isRecord(input))invalid(partial?'patch must be an object':'profile must be an object');const extra=Object.keys(input).filter(k=>!PROFILE_FIELDS.includes(k));if(extra.length)invalid(`unsupported profile field(s): ${extra.sort().join(', ')}`);for(const key of PROFILE_FIELDS){if(!partial&&!(key in input))invalid(`${key} is required`);if(input[key]!==undefined&&input[key]!==null&&typeof input[key]!=='string')invalid(`${key} must be a string or null`)}if(input.name===null)invalid('name must be a string');return input}
export function parseCreateAiAgentProfileCommandV1(input:unknown):CreateAiAgentProfileCommandV1{const v=envelope(input,CREATE_AI_AGENT_PROFILE_COMMAND_V1,'calling.CreateAiAgentProfileCommand.',['contract','profile']);profileValues(v.profile,false);if(typeof(v.profile as Record<string,unknown>).name!=='string')invalid('name must be a string');return v as unknown as CreateAiAgentProfileCommandV1}
export function parseUpdateAiAgentProfileCommandV1(input:unknown):UpdateAiAgentProfileCommandV1{const v=envelope(input,UPDATE_AI_AGENT_PROFILE_COMMAND_V1,'calling.UpdateAiAgentProfileCommand.',['contract','profileId','patch']);if(typeof v.profileId!=='string')invalid('profileId must be a string');profileValues(v.patch,true);return v as unknown as UpdateAiAgentProfileCommandV1}
export function parseDeleteAiAgentProfileCommandV1(input:unknown):DeleteAiAgentProfileCommandV1{const v=envelope(input,DELETE_AI_AGENT_PROFILE_COMMAND_V1,'calling.DeleteAiAgentProfileCommand.',['contract','profileId']);if(typeof v.profileId!=='string')invalid('profileId must be a string');return v as unknown as DeleteAiAgentProfileCommandV1}
