export const OUTBOUND_SHADOW_PLAN_SCHEMA_VERSION = 'max-outbound-shadow-plan-v1'
export const OUTBOUND_SHADOW_PLANNING_ACCOUNTS = 'MAX_PERSONAL_OUTBOUND_SHADOW_PLANNING_ACCOUNTS'
export const MAX_SHADOW_TEXT_BYTES = 65_536
