export const DEACTIVATE_CONTACT_PHONE_COMMAND_V1='contacts.DeactivateContactPhoneCommand.v1' as const
export const DEACTIVATE_CONTACT_PHONE_RESULT_V1='contacts.DeactivateContactPhoneResult.v1' as const
export const CREATE_CONTACT_PHONE_COMMAND_V1='contacts.CreateContactPhoneCommand.v1' as const
export const CREATE_CONTACT_PHONE_RESULT_V1='contacts.CreateContactPhoneResult.v1' as const
export interface DeactivateContactPhoneCommandV1{contract:typeof DEACTIVATE_CONTACT_PHONE_COMMAND_V1;contactPhoneId:string}
export interface DeactivateContactPhoneResultV1{contract:typeof DEACTIVATE_CONTACT_PHONE_RESULT_V1}
export interface CreateContactPhoneCommandV1{contract:typeof CREATE_CONTACT_PHONE_COMMAND_V1;contactId:string;phone:string;source:'yandex';isPrimary:boolean}
export interface CreateContactPhoneResultV1{contract:typeof CREATE_CONTACT_PHONE_RESULT_V1;contactPhoneId:string}
export class ContactPhoneCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:ContactPhoneCommandValidationError['code'],message:string){super(message);this.name='ContactPhoneCommandValidationError';this.code=code}}
const isRecord=(value:unknown):value is Record<string,unknown>=>typeof value==='object'&&value!==null&&!Array.isArray(value);function invalid(message:string):never{throw new ContactPhoneCommandValidationError('INVALID_CONTRACT',message)}function parse(input:unknown,expected:string,prefix:string,fields:string[]){if(!isRecord(input))invalid('command must be an object');const extra=Object.keys(input).filter(key=>!fields.includes(key));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new ContactPhoneCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}function string(value:unknown,field:string){if(typeof value!=='string'||value.trim()==='')invalid(`${field} is required`)}
export function parseDeactivateContactPhoneCommandV1(input:unknown):DeactivateContactPhoneCommandV1{const value=parse(input,DEACTIVATE_CONTACT_PHONE_COMMAND_V1,'contacts.DeactivateContactPhoneCommand.',['contract','contactPhoneId']);string(value.contactPhoneId,'contactPhoneId');return value as unknown as DeactivateContactPhoneCommandV1}
export function parseCreateContactPhoneCommandV1(input:unknown):CreateContactPhoneCommandV1{const value=parse(input,CREATE_CONTACT_PHONE_COMMAND_V1,'contacts.CreateContactPhoneCommand.',['contract','contactId','phone','source','isPrimary']);string(value.contactId,'contactId');string(value.phone,'phone');if(value.source!=='yandex')invalid('source is invalid');if(typeof value.isPrimary!=='boolean')invalid('isPrimary must be a boolean');return value as unknown as CreateContactPhoneCommandV1}
