export const ATTACH_MANUAL_KNOWLEDGE_SOURCE_COMMAND_V1='ai_knowledge.AttachManualKnowledgeSourceCommand.v1' as const
export const ATTACH_MANUAL_KNOWLEDGE_SOURCE_RESULT_V1='ai_knowledge.AttachManualKnowledgeSourceResult.v1' as const
export const DISABLE_KNOWLEDGE_SOURCES_COMMAND_V1='ai_knowledge.DisableKnowledgeSourcesCommand.v1' as const
export const DISABLE_KNOWLEDGE_SOURCES_RESULT_V1='ai_knowledge.DisableKnowledgeSourcesResult.v1' as const
export const KNOWLEDGE_SOURCE_CHANNELS_V1=['whatsapp','telegram','max']as const;export type KnowledgeSourceChannelV1=typeof KNOWLEDGE_SOURCE_CHANNELS_V1[number]
export interface AttachManualKnowledgeSourceCommandV1{contract:typeof ATTACH_MANUAL_KNOWLEDGE_SOURCE_COMMAND_V1;sourceId:string;itemId:string;actorId:string}
export interface AttachManualKnowledgeSourceResultV1{contract:typeof ATTACH_MANUAL_KNOWLEDGE_SOURCE_RESULT_V1;attached:true}
export interface DisableKnowledgeSourcesCommandV1{contract:typeof DISABLE_KNOWLEDGE_SOURCES_COMMAND_V1;channel:KnowledgeSourceChannelV1;connectionId:string}
export interface DisableKnowledgeSourcesResultV1{contract:typeof DISABLE_KNOWLEDGE_SOURCES_RESULT_V1;disabledCount:number}
export class KnowledgeSourceCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:KnowledgeSourceCommandValidationError['code'],message:string){super(message);this.name='KnowledgeSourceCommandValidationError';this.code=code}}
const CHANNELS=new Set<string>(KNOWLEDGE_SOURCE_CHANNELS_V1),isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v),nonEmpty=(v:unknown):v is string=>typeof v==='string'&&v.trim()!=='';function invalid(m:string):never{throw new KnowledgeSourceCommandValidationError('INVALID_CONTRACT',m)}function envelope(input:unknown,expected:string,prefix:string,allowed:string[]):Record<string,unknown>{if(!isRecord(input))invalid('command must be an object');const extra=Object.keys(input).filter(k=>!allowed.includes(k));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new KnowledgeSourceCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}
export function parseAttachManualKnowledgeSourceCommandV1(input:unknown):AttachManualKnowledgeSourceCommandV1{const value=envelope(input,ATTACH_MANUAL_KNOWLEDGE_SOURCE_COMMAND_V1,'ai_knowledge.AttachManualKnowledgeSourceCommand.',['contract','sourceId','itemId','actorId']);for(const key of['sourceId','itemId','actorId'])if(!nonEmpty(value[key]))invalid(`${key} is required`);return value as unknown as AttachManualKnowledgeSourceCommandV1}
export function parseDisableKnowledgeSourcesCommandV1(input:unknown):DisableKnowledgeSourcesCommandV1{const value=envelope(input,DISABLE_KNOWLEDGE_SOURCES_COMMAND_V1,'ai_knowledge.DisableKnowledgeSourcesCommand.',['contract','channel','connectionId']);if(typeof value.channel!=='string'||!CHANNELS.has(value.channel))invalid('channel is invalid');if(!nonEmpty(value.connectionId))invalid('connectionId is required');return value as unknown as DisableKnowledgeSourcesCommandV1}
