export const VERIFY_KNOWLEDGE_ITEM_COMMAND_V1='ai_knowledge.VerifyKnowledgeItemCommand.v1' as const
export const VERIFY_KNOWLEDGE_ITEM_RESULT_V1='ai_knowledge.VerifyKnowledgeItemResult.v1' as const
export const APPLY_KNOWLEDGE_ITEM_COACH_EDIT_COMMAND_V1='ai_knowledge.ApplyKnowledgeItemCoachEditCommand.v1' as const
export const APPLY_KNOWLEDGE_ITEM_COACH_EDIT_RESULT_V1='ai_knowledge.ApplyKnowledgeItemCoachEditResult.v1' as const
export interface VerifyKnowledgeItemCommandV1{contract:typeof VERIFY_KNOWLEDGE_ITEM_COMMAND_V1;itemId:string;verifiedBy:string|null}
export interface VerifyKnowledgeItemResultV1{contract:typeof VERIFY_KNOWLEDGE_ITEM_RESULT_V1;updated:true}
export interface ApplyKnowledgeItemCoachEditCommandV1{contract:typeof APPLY_KNOWLEDGE_ITEM_COACH_EDIT_COMMAND_V1;itemId:string;canonicalStatement:string;verifiedBy:string|null}
export interface ApplyKnowledgeItemCoachEditResultV1{contract:typeof APPLY_KNOWLEDGE_ITEM_COACH_EDIT_RESULT_V1;updated:true}
export class KnowledgeItemReviewCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:KnowledgeItemReviewCommandValidationError['code'],message:string){super(message);this.name='KnowledgeItemReviewCommandValidationError';this.code=code}}
const isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);function invalid(message:string):never{throw new KnowledgeItemReviewCommandValidationError('INVALID_CONTRACT',message)}function envelope(input:unknown,expected:string,prefix:string,fields:string[]):Record<string,unknown>{if(!isRecord(input))invalid('command must be an object');const extra=Object.keys(input).filter(k=>!fields.includes(k));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new KnowledgeItemReviewCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}function actor(value:unknown):asserts value is string|null{if(value!==null&&typeof value!=='string')invalid('verifiedBy must be a string or null')}
export function parseVerifyKnowledgeItemCommandV1(input:unknown):VerifyKnowledgeItemCommandV1{const value=envelope(input,VERIFY_KNOWLEDGE_ITEM_COMMAND_V1,'ai_knowledge.VerifyKnowledgeItemCommand.',['contract','itemId','verifiedBy']);if(typeof value.itemId!=='string')invalid('itemId must be a string');actor(value.verifiedBy);return value as unknown as VerifyKnowledgeItemCommandV1}
export function parseApplyKnowledgeItemCoachEditCommandV1(input:unknown):ApplyKnowledgeItemCoachEditCommandV1{const value=envelope(input,APPLY_KNOWLEDGE_ITEM_COACH_EDIT_COMMAND_V1,'ai_knowledge.ApplyKnowledgeItemCoachEditCommand.',['contract','itemId','canonicalStatement','verifiedBy']);if(typeof value.itemId!=='string')invalid('itemId must be a string');if(typeof value.canonicalStatement!=='string')invalid('canonicalStatement must be a string');actor(value.verifiedBy);return value as unknown as ApplyKnowledgeItemCoachEditCommandV1}
