export const DELIVER_QUEUED_MESSAGES_FOR_CONNECTION_COMMAND_V1='messaging.DeliverQueuedMessagesForConnectionCommand.v1' as const
export const DELETE_QUEUED_MESSAGES_FOR_CONNECTION_COMMAND_V1='messaging.DeleteQueuedMessagesForConnectionCommand.v1' as const
export const DELETE_LEGACY_EXTERNAL_CONVERSATIONS_COMMAND_V1='messaging.DeleteLegacyExternalConversationsCommand.v1' as const
export const DELETE_CONVERSATIONS_BY_ID_COMMAND_V1='messaging.DeleteConversationsByIdCommand.v1' as const
export const CHANNEL_MAINTENANCE_RESULT_V1='messaging.ChannelMaintenanceResult.v1' as const
export interface ConversationTimestampV1{id:string;lastMessageAt:Date}
export interface DeliverQueuedMessagesForConnectionCommandV1{contract:typeof DELIVER_QUEUED_MESSAGES_FOR_CONNECTION_COMMAND_V1;connectionId:string;messageIds:string[];conversations:ConversationTimestampV1[]}
export interface DeleteQueuedMessagesForConnectionCommandV1{contract:typeof DELETE_QUEUED_MESSAGES_FOR_CONNECTION_COMMAND_V1;connectionId:string}
export interface DeleteLegacyExternalConversationsCommandV1{contract:typeof DELETE_LEGACY_EXTERNAL_CONVERSATIONS_COMMAND_V1}
export interface DeleteConversationsByIdCommandV1{contract:typeof DELETE_CONVERSATIONS_BY_ID_COMMAND_V1;conversationIds:string[]}
export interface ChannelMaintenanceResultV1{contract:typeof CHANNEL_MAINTENANCE_RESULT_V1;completed:true}
export class ChannelMaintenanceValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:ChannelMaintenanceValidationError['code'],message:string){super(message);this.name='ChannelMaintenanceValidationError';this.code=code}}
const record=(value:unknown):value is Record<string,unknown>=>typeof value==='object'&&value!==null&&!Array.isArray(value)
function invalid(message:string):never{throw new ChannelMaintenanceValidationError('INVALID_CONTRACT',message)}
function requireString(value:unknown,key:string):void{if(typeof value!=='string'||value.trim()==='')invalid(`${key} is required`)}
function requireIds(value:unknown,key:string):void{if(!Array.isArray(value)||value.length===0||value.some(id=>typeof id!=='string'||id.trim()==='')||new Set(value).size!==value.length)invalid(`${key} must be a non-empty unique string array`)}
function env(input:unknown,expected:string,fields:string[]):Record<string,unknown>{if(!record(input))invalid('command must be an object');const extra=Object.keys(input).filter(key=>!fields.includes(key));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(expected.replace(/v1$/,'')))throw new ChannelMaintenanceValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}
export function parseDeliverQueuedMessagesForConnectionCommandV1(input:unknown):DeliverQueuedMessagesForConnectionCommandV1{const v=env(input,DELIVER_QUEUED_MESSAGES_FOR_CONNECTION_COMMAND_V1,['contract','connectionId','messageIds','conversations']);requireString(v.connectionId,'connectionId');requireIds(v.messageIds,'messageIds');const conversations=v.conversations;if(!Array.isArray(conversations)||conversations.length===0)invalid('conversations must be non-empty');for(const item of conversations){if(!record(item)||Object.keys(item).some(key=>!['id','lastMessageAt'].includes(key)))invalid('invalid conversation');requireString(item.id,'conversation.id');if(!(item.lastMessageAt instanceof Date)||Number.isNaN(item.lastMessageAt.getTime()))invalid('conversation.lastMessageAt must be a valid Date')}return v as unknown as DeliverQueuedMessagesForConnectionCommandV1}
export function parseDeleteQueuedMessagesForConnectionCommandV1(input:unknown):DeleteQueuedMessagesForConnectionCommandV1{const v=env(input,DELETE_QUEUED_MESSAGES_FOR_CONNECTION_COMMAND_V1,['contract','connectionId']);requireString(v.connectionId,'connectionId');return v as unknown as DeleteQueuedMessagesForConnectionCommandV1}
export function parseDeleteLegacyExternalConversationsCommandV1(input:unknown):DeleteLegacyExternalConversationsCommandV1{return env(input,DELETE_LEGACY_EXTERNAL_CONVERSATIONS_COMMAND_V1,['contract'])as unknown as DeleteLegacyExternalConversationsCommandV1}
export function parseDeleteConversationsByIdCommandV1(input:unknown):DeleteConversationsByIdCommandV1{const v=env(input,DELETE_CONVERSATIONS_BY_ID_COMMAND_V1,['contract','conversationIds']);requireIds(v.conversationIds,'conversationIds');return v as unknown as DeleteConversationsByIdCommandV1}
