export const CREATE_CHANNEL_MESSAGE_COMMAND_V1='messaging.CreateChannelMessageCommand.v1' as const
export const CREATE_CHANNEL_MESSAGE_RESULT_V1='messaging.CreateChannelMessageResult.v1' as const
export const PATCH_MESSAGE_DELIVERY_COMMAND_V1='messaging.PatchMessageDeliveryCommand.v1' as const
export const PATCH_MESSAGE_DELIVERY_RESULT_V1='messaging.PatchMessageDeliveryResult.v1' as const
export type ChannelMessageDirectionV1='inbound'|'outbound'
export type ChannelMessageTypeV1='text'|'image'|'audio'|'video'|'sticker'|'voice'|'document'|'system'|'call'
export type ChannelMessageJsonV1=string|number|boolean|null|ChannelMessageJsonV1[]|{[key:string]:ChannelMessageJsonV1}
export interface ChannelMessageRecordV1{id:string;chatId:string;direction:ChannelMessageDirectionV1|'system';type:ChannelMessageTypeV1;content:string;status:'queued'|'sent'|'delivered'|'read'|'failed';externalId:string|null;metadata:ChannelMessageJsonV1;sentAt:Date;createdAt:Date;updatedAt:Date;channel:'telegram'|'whatsapp'|'max'|'phone'|'avito'|null;aiStatus:'pending'|'processing'|'done'|'skipped'|'failed'|null;clientMessageId:string|null}
export interface CreateChannelMessageCommandV1{contract:typeof CREATE_CHANNEL_MESSAGE_COMMAND_V1;chatId:string;direction:ChannelMessageDirectionV1;type:ChannelMessageTypeV1;content:string;externalId:string;sentAt:Date;channel?:'whatsapp';status?:'delivered';metadata?:unknown}
export interface CreateChannelMessageResultV1{contract:typeof CREATE_CHANNEL_MESSAGE_RESULT_V1;message:ChannelMessageRecordV1}
export interface PatchMessageDeliveryCommandV1{contract:typeof PATCH_MESSAGE_DELIVERY_COMMAND_V1;messageId:string;externalId:string;status?:'delivered';sentAt?:Date}
export interface PatchMessageDeliveryResultV1{contract:typeof PATCH_MESSAGE_DELIVERY_RESULT_V1;updated:true}
export class ChannelMessageCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:ChannelMessageCommandValidationError['code'],message:string){super(message);this.name='ChannelMessageCommandValidationError';this.code=code}}
const TYPES=new Set(['text','image','audio','video','sticker','voice','document','system','call']),isRecord=(value:unknown):value is Record<string,unknown>=>typeof value==='object'&&value!==null&&!Array.isArray(value)
function invalid(message:string):never{throw new ChannelMessageCommandValidationError('INVALID_CONTRACT',message)}
function envelope(input:unknown,expected:string,prefix:string,fields:string[]):Record<string,unknown>{if(!isRecord(input))invalid('command must be an object');const extra=Object.keys(input).filter(key=>!fields.includes(key));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new ChannelMessageCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}
function string(value:unknown,key:string){if(typeof value!=='string'||value.trim()==='')invalid(`${key} is required`)}
function date(value:unknown,key:string){if(!(value instanceof Date)||Number.isNaN(value.getTime()))invalid(`${key} must be a valid Date`)}
export function parseCreateChannelMessageCommandV1(input:unknown):CreateChannelMessageCommandV1{const value=envelope(input,CREATE_CHANNEL_MESSAGE_COMMAND_V1,'messaging.CreateChannelMessageCommand.',['contract','chatId','direction','type','content','externalId','sentAt','channel','status','metadata']);string(value.chatId,'chatId');if(value.direction!=='inbound'&&value.direction!=='outbound')invalid('direction is invalid');if(typeof value.type!=='string'||!TYPES.has(value.type))invalid('type is invalid');if(typeof value.content!=='string')invalid('content must be a string');string(value.externalId,'externalId');date(value.sentAt,'sentAt');if(value.channel!==undefined&&value.channel!=='whatsapp')invalid('channel is invalid');if(value.status!==undefined&&value.status!=='delivered')invalid('status is invalid');return value as unknown as CreateChannelMessageCommandV1}
export function parsePatchMessageDeliveryCommandV1(input:unknown):PatchMessageDeliveryCommandV1{const value=envelope(input,PATCH_MESSAGE_DELIVERY_COMMAND_V1,'messaging.PatchMessageDeliveryCommand.',['contract','messageId','externalId','status','sentAt']);string(value.messageId,'messageId');string(value.externalId,'externalId');if(value.status!==undefined&&value.status!=='delivered')invalid('status is invalid');if(value.sentAt!==undefined)date(value.sentAt,'sentAt');return value as unknown as PatchMessageDeliveryCommandV1}
