export const UPSERT_CHANNEL_CONVERSATION_COMMAND_V1='messaging.UpsertChannelConversationCommand.v1' as const
export const UPSERT_CHANNEL_CONVERSATION_RESULT_V1='messaging.UpsertChannelConversationResult.v1' as const
export const PATCH_CHANNEL_CONVERSATION_COMMAND_V1='messaging.PatchChannelConversationCommand.v1' as const
export const PATCH_CHANNEL_CONVERSATION_RESULT_V1='messaging.PatchChannelConversationResult.v1' as const
export interface UpsertChannelConversationCommandV1{contract:typeof UPSERT_CHANNEL_CONVERSATION_COMMAND_V1;externalChatId:string;channel:'whatsapp';name:string|null;chatType:'group'|'private';metadata:unknown}
export interface UpsertChannelConversationResultV1{contract:typeof UPSERT_CHANNEL_CONVERSATION_RESULT_V1;conversation:unknown}
export type ChannelConversationSelectorV1={chatId:string}|{externalChatId:string}
export interface ChannelConversationPatchV1{name?:string|null;driverId?:string|null;externalChatId?:string;lastMessageAt?:Date}
export interface PatchChannelConversationCommandV1{contract:typeof PATCH_CHANNEL_CONVERSATION_COMMAND_V1;selector:ChannelConversationSelectorV1;patch:ChannelConversationPatchV1}
export interface PatchChannelConversationResultV1{contract:typeof PATCH_CHANNEL_CONVERSATION_RESULT_V1;conversation:unknown}
export class ChannelConversationCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:ChannelConversationCommandValidationError['code'],message:string){super(message);this.name='ChannelConversationCommandValidationError';this.code=code}}
const isRecord=(value:unknown):value is Record<string,unknown>=>typeof value==='object'&&value!==null&&!Array.isArray(value)
function invalid(message:string):never{throw new ChannelConversationCommandValidationError('INVALID_CONTRACT',message)}
function envelope(input:unknown,expected:string,prefix:string,fields:string[]):Record<string,unknown>{if(!isRecord(input))invalid('command must be an object');const extra=Object.keys(input).filter(key=>!fields.includes(key));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new ChannelConversationCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}
function string(value:unknown,key:string){if(typeof value!=='string'||value.trim()==='')invalid(`${key} is required`)}
export function parseUpsertChannelConversationCommandV1(input:unknown):UpsertChannelConversationCommandV1{const value=envelope(input,UPSERT_CHANNEL_CONVERSATION_COMMAND_V1,'messaging.UpsertChannelConversationCommand.',['contract','externalChatId','channel','name','chatType','metadata']);string(value.externalChatId,'externalChatId');if(value.channel!=='whatsapp')invalid('channel is invalid');if(value.name!==null&&typeof value.name!=='string')invalid('name must be a string or null');if(value.chatType!=='group'&&value.chatType!=='private')invalid('chatType is invalid');return value as unknown as UpsertChannelConversationCommandV1}
export function parsePatchChannelConversationCommandV1(input:unknown):PatchChannelConversationCommandV1{const value=envelope(input,PATCH_CHANNEL_CONVERSATION_COMMAND_V1,'messaging.PatchChannelConversationCommand.',['contract','selector','patch']);if(!isRecord(value.selector))invalid('selector must be an object');const selectorKeys=Object.keys(value.selector);if(selectorKeys.length!==1||!['chatId','externalChatId'].includes(selectorKeys[0]))invalid('selector must contain exactly one supported key');string(value.selector[selectorKeys[0]],`selector.${selectorKeys[0]}`);if(!isRecord(value.patch))invalid('patch must be an object');const fields=['name','driverId','externalChatId','lastMessageAt'],extra=Object.keys(value.patch).filter(key=>!fields.includes(key));if(extra.length)invalid(`unsupported patch field(s): ${extra.sort().join(', ')}`);if(Object.keys(value.patch).length===0)invalid('patch must not be empty');for(const key of['name','driverId']){const candidate=value.patch[key];if(candidate!==undefined&&candidate!==null&&typeof candidate!=='string')invalid(`patch.${key} must be a string or null`)}if(value.patch.externalChatId!==undefined)string(value.patch.externalChatId,'patch.externalChatId');if(value.patch.lastMessageAt!==undefined&&(!(value.patch.lastMessageAt instanceof Date)||Number.isNaN(value.patch.lastMessageAt.getTime())))invalid('patch.lastMessageAt must be a valid Date');return value as unknown as PatchChannelConversationCommandV1}
