export const CREATE_COMMUNICATION_TRIGGER_COMMAND_V1='messaging.CreateCommunicationTriggerCommand.v1' as const
export const CREATE_COMMUNICATION_TRIGGER_RESULT_V1='messaging.CreateCommunicationTriggerResult.v1' as const
export const UPDATE_COMMUNICATION_TRIGGER_COMMAND_V1='messaging.UpdateCommunicationTriggerCommand.v1' as const
export const UPDATE_COMMUNICATION_TRIGGER_RESULT_V1='messaging.UpdateCommunicationTriggerResult.v1' as const
export const DELETE_COMMUNICATION_TRIGGER_COMMAND_V1='messaging.DeleteCommunicationTriggerCommand.v1' as const
export const DELETE_COMMUNICATION_TRIGGER_RESULT_V1='messaging.DeleteCommunicationTriggerResult.v1' as const
export interface CreateCommunicationTriggerDataV1{name:string;condition:string;threshold:number;action:string;messageTemplate?:string;channel:string}
export interface UpdateCommunicationTriggerPatchV1{name?:string;condition?:string;threshold?:number;action?:string;messageTemplate?:string;channel?:string;isActive?:boolean}
export interface CreateCommunicationTriggerCommandV1{contract:typeof CREATE_COMMUNICATION_TRIGGER_COMMAND_V1;data:CreateCommunicationTriggerDataV1}
export interface CreateCommunicationTriggerResultV1{contract:typeof CREATE_COMMUNICATION_TRIGGER_RESULT_V1;created:true}
export interface UpdateCommunicationTriggerCommandV1{contract:typeof UPDATE_COMMUNICATION_TRIGGER_COMMAND_V1;triggerId:string;patch:UpdateCommunicationTriggerPatchV1}
export interface UpdateCommunicationTriggerResultV1{contract:typeof UPDATE_COMMUNICATION_TRIGGER_RESULT_V1;updated:true}
export interface DeleteCommunicationTriggerCommandV1{contract:typeof DELETE_COMMUNICATION_TRIGGER_COMMAND_V1;triggerId:string}
export interface DeleteCommunicationTriggerResultV1{contract:typeof DELETE_COMMUNICATION_TRIGGER_RESULT_V1;deleted:true}
export class CommunicationTriggerCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:CommunicationTriggerCommandValidationError['code'],message:string){super(message);this.name='CommunicationTriggerCommandValidationError';this.code=code}}
const isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);function invalid(m:string):never{throw new CommunicationTriggerCommandValidationError('INVALID_CONTRACT',m)}function envelope(input:unknown,expected:string,prefix:string,fields:string[]):Record<string,unknown>{if(!isRecord(input))invalid('command must be an object');const extra=Object.keys(input).filter(k=>!fields.includes(k));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new CommunicationTriggerCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}function object(value:unknown,key:string,fields:string[]):Record<string,unknown>{if(!isRecord(value))invalid(`${key} must be an object`);const extra=Object.keys(value).filter(k=>!fields.includes(k));if(extra.length)invalid(`unsupported ${key} field(s): ${extra.sort().join(', ')}`);return value}function string(value:unknown,key:string){if(typeof value!=='string')invalid(`${key} must be a string`)}
export function parseCreateCommunicationTriggerCommandV1(input:unknown):CreateCommunicationTriggerCommandV1{const v=envelope(input,CREATE_COMMUNICATION_TRIGGER_COMMAND_V1,'messaging.CreateCommunicationTriggerCommand.',['contract','data']),data=object(v.data,'data',['name','condition','threshold','action','messageTemplate','channel']);for(const key of['name','condition','action','channel'])string(data[key],`data.${key}`);if(typeof data.threshold!=='number')invalid('data.threshold must be a number');if(data.messageTemplate!==undefined)string(data.messageTemplate,'data.messageTemplate');return v as unknown as CreateCommunicationTriggerCommandV1}
export function parseUpdateCommunicationTriggerCommandV1(input:unknown):UpdateCommunicationTriggerCommandV1{const v=envelope(input,UPDATE_COMMUNICATION_TRIGGER_COMMAND_V1,'messaging.UpdateCommunicationTriggerCommand.',['contract','triggerId','patch']),patch=object(v.patch,'patch',['name','condition','threshold','action','messageTemplate','channel','isActive']);string(v.triggerId,'triggerId');for(const key of['name','condition','action','messageTemplate','channel'])if(patch[key]!==undefined)string(patch[key],`patch.${key}`);if(patch.threshold!==undefined&&typeof patch.threshold!=='number')invalid('patch.threshold must be a number');if(patch.isActive!==undefined&&typeof patch.isActive!=='boolean')invalid('patch.isActive must be a boolean');return v as unknown as UpdateCommunicationTriggerCommandV1}
export function parseDeleteCommunicationTriggerCommandV1(input:unknown):DeleteCommunicationTriggerCommandV1{const v=envelope(input,DELETE_COMMUNICATION_TRIGGER_COMMAND_V1,'messaging.DeleteCommunicationTriggerCommand.',['contract','triggerId']);string(v.triggerId,'triggerId');return v as unknown as DeleteCommunicationTriggerCommandV1}
