export const DELETE_MESSAGE_COMMAND_V1='messaging.DeleteMessageCommand.v1' as const
export const DELETE_MESSAGE_RESULT_V1='messaging.DeleteMessageResult.v1' as const
export const REPLACE_EXTERNAL_MESSAGE_COMMAND_V1='messaging.ReplaceExternalMessageCommand.v1' as const
export const REPLACE_EXTERNAL_MESSAGE_RESULT_V1='messaging.ReplaceExternalMessageResult.v1' as const
export const UPSERT_EXTERNAL_MESSAGE_COMMAND_V1='messaging.UpsertExternalMessageCommand.v1' as const
export const UPSERT_EXTERNAL_MESSAGE_RESULT_V1='messaging.UpsertExternalMessageResult.v1' as const
export type ExternalMessageDirectionV1='inbound'|'outbound';export type ExternalMessageTypeV1='text'|'image'|'audio'|'video'|'sticker'|'voice'|'document'|'system'|'call'
export interface ExternalMessageRecordV1{id:string;chatId:string;direction:ExternalMessageDirectionV1|'system';type:ExternalMessageTypeV1;content:string;status:'queued'|'sent'|'delivered'|'read'|'failed';externalId:string|null;metadata:unknown;sentAt:Date;createdAt:Date;updatedAt:Date;channel:'telegram'|'whatsapp'|'max'|'phone'|'avito'|null;aiStatus:'pending'|'processing'|'done'|'skipped'|'failed'|null;clientMessageId:string|null}
export interface DeleteMessageCommandV1{contract:typeof DELETE_MESSAGE_COMMAND_V1;messageId:string};export interface DeleteMessageResultV1{contract:typeof DELETE_MESSAGE_RESULT_V1;deleted:true}
export interface ReplaceExternalMessageCommandV1{contract:typeof REPLACE_EXTERNAL_MESSAGE_COMMAND_V1;messageId:string;externalId:string;type:ExternalMessageTypeV1;content:string;sentAt:Date;metadata:unknown};export interface ReplaceExternalMessageResultV1{contract:typeof REPLACE_EXTERNAL_MESSAGE_RESULT_V1;message:ExternalMessageRecordV1}
export interface UpsertExternalMessageCommandV1{contract:typeof UPSERT_EXTERNAL_MESSAGE_COMMAND_V1;lookupExternalId:string;chatId:string;direction:ExternalMessageDirectionV1;type:ExternalMessageTypeV1;content:string;channel:'max';externalId:string|null;sentAt:Date;metadata:unknown};export interface UpsertExternalMessageResultV1{contract:typeof UPSERT_EXTERNAL_MESSAGE_RESULT_V1;message:ExternalMessageRecordV1}
export class ExternalMessageCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:ExternalMessageCommandValidationError['code'],message:string){super(message);this.name='ExternalMessageCommandValidationError';this.code=code}}
const TYPES=new Set(['text','image','audio','video','sticker','voice','document','system','call']),isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);function invalid(m:string):never{throw new ExternalMessageCommandValidationError('INVALID_CONTRACT',m)}function envelope(input:unknown,expected:string,prefix:string,fields:string[]):Record<string,unknown>{if(!isRecord(input))invalid('command must be an object');const extra=Object.keys(input).filter(k=>!fields.includes(k));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new ExternalMessageCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}function string(v:unknown,key:string){if(typeof v!=='string'||v.trim()==='')invalid(`${key} is required`)}function type(v:unknown){if(typeof v!=='string'||!TYPES.has(v))invalid('type is invalid')}function date(v:unknown,key:string){if(!(v instanceof Date))invalid(`${key} must be a Date`)}
export function parseDeleteMessageCommandV1(input:unknown):DeleteMessageCommandV1{const v=envelope(input,DELETE_MESSAGE_COMMAND_V1,'messaging.DeleteMessageCommand.',['contract','messageId']);string(v.messageId,'messageId');return v as unknown as DeleteMessageCommandV1}
export function parseReplaceExternalMessageCommandV1(input:unknown):ReplaceExternalMessageCommandV1{const v=envelope(input,REPLACE_EXTERNAL_MESSAGE_COMMAND_V1,'messaging.ReplaceExternalMessageCommand.',['contract','messageId','externalId','type','content','sentAt','metadata']);string(v.messageId,'messageId');string(v.externalId,'externalId');type(v.type);if(typeof v.content!=='string')invalid('content must be a string');date(v.sentAt,'sentAt');return v as unknown as ReplaceExternalMessageCommandV1}
export function parseUpsertExternalMessageCommandV1(input:unknown):UpsertExternalMessageCommandV1{const v=envelope(input,UPSERT_EXTERNAL_MESSAGE_COMMAND_V1,'messaging.UpsertExternalMessageCommand.',['contract','lookupExternalId','chatId','direction','type','content','channel','externalId','sentAt','metadata']);string(v.lookupExternalId,'lookupExternalId');string(v.chatId,'chatId');if(v.direction!=='inbound'&&v.direction!=='outbound')invalid('direction is invalid');type(v.type);if(typeof v.content!=='string')invalid('content must be a string');if(v.channel!=='max')invalid('channel is invalid');if(v.externalId!==null&&typeof v.externalId!=='string')invalid('externalId must be a string or null');date(v.sentAt,'sentAt');return v as unknown as UpsertExternalMessageCommandV1}
