export const PATCH_EXTERNAL_CONVERSATION_COMMAND_V1='messaging.PatchExternalConversationCommand.v1' as const
export const PATCH_EXTERNAL_CONVERSATION_RESULT_V1='messaging.PatchExternalConversationResult.v1' as const
export const CREATE_EXTERNAL_CONVERSATION_COMMAND_V1='messaging.CreateExternalConversationCommand.v1' as const
export const CREATE_EXTERNAL_CONVERSATION_RESULT_V1='messaging.CreateExternalConversationResult.v1' as const
export interface ExternalConversationPatchV1{externalChatId?:string;name?:string;lastMessageAt?:Date;metadata?:unknown}
export interface PatchExternalConversationCommandV1{contract:typeof PATCH_EXTERNAL_CONVERSATION_COMMAND_V1;chatId:string;patch:ExternalConversationPatchV1};export interface PatchExternalConversationResultV1{contract:typeof PATCH_EXTERNAL_CONVERSATION_RESULT_V1;conversation:unknown}
export interface CreateExternalConversationCommandV1{contract:typeof CREATE_EXTERNAL_CONVERSATION_COMMAND_V1;channel:'max';externalChatId:string;name:string;lastMessageAt:Date;status:'new';metadata:unknown};export interface CreateExternalConversationResultV1{contract:typeof CREATE_EXTERNAL_CONVERSATION_RESULT_V1;conversation:unknown}
export class ExternalConversationCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:ExternalConversationCommandValidationError['code'],message:string){super(message);this.name='ExternalConversationCommandValidationError';this.code=code}}
const isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);function invalid(m:string):never{throw new ExternalConversationCommandValidationError('INVALID_CONTRACT',m)}function envelope(input:unknown,expected:string,prefix:string,fields:string[]):Record<string,unknown>{if(!isRecord(input))invalid('command must be an object');const extra=Object.keys(input).filter(k=>!fields.includes(k));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new ExternalConversationCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}function string(v:unknown,key:string){if(typeof v!=='string'||v.trim()==='')invalid(`${key} is required`)}
export function parsePatchExternalConversationCommandV1(input:unknown):PatchExternalConversationCommandV1{const v=envelope(input,PATCH_EXTERNAL_CONVERSATION_COMMAND_V1,'messaging.PatchExternalConversationCommand.',['contract','chatId','patch']);string(v.chatId,'chatId');if(!isRecord(v.patch))invalid('patch must be an object');const extra=Object.keys(v.patch).filter(k=>!['externalChatId','name','lastMessageAt','metadata'].includes(k));if(extra.length)invalid(`unsupported patch field(s): ${extra.sort().join(', ')}`);for(const key of['externalChatId','name'])if(v.patch[key]!==undefined)string(v.patch[key],`patch.${key}`);if(v.patch.lastMessageAt!==undefined&&!(v.patch.lastMessageAt instanceof Date))invalid('patch.lastMessageAt must be a Date');return v as unknown as PatchExternalConversationCommandV1}
export function parseCreateExternalConversationCommandV1(input:unknown):CreateExternalConversationCommandV1{const v=envelope(input,CREATE_EXTERNAL_CONVERSATION_COMMAND_V1,'messaging.CreateExternalConversationCommand.',['contract','channel','externalChatId','name','lastMessageAt','status','metadata']);if(v.channel!=='max')invalid('channel is invalid');string(v.externalChatId,'externalChatId');string(v.name,'name');if(!(v.lastMessageAt instanceof Date))invalid('lastMessageAt must be a Date');if(v.status!=='new')invalid('status is invalid');return v as unknown as CreateExternalConversationCommandV1}
