export const DELETE_HISTORY_IMPORT_JOB_COMMAND_V1='messaging.DeleteHistoryImportJobCommand.v1' as const
export const DELETE_HISTORY_IMPORT_JOB_RESULT_V1='messaging.DeleteHistoryImportJobResult.v1' as const
export const UPDATE_HISTORY_IMPORT_JOB_COMMAND_V1='messaging.UpdateHistoryImportJobCommand.v1' as const
export const UPDATE_HISTORY_IMPORT_JOB_RESULT_V1='messaging.UpdateHistoryImportJobResult.v1' as const
export const DELETE_HISTORY_IMPORT_JOBS_FOR_CONNECTION_COMMAND_V1='messaging.DeleteHistoryImportJobsForConnectionCommand.v1' as const
export const DELETE_HISTORY_IMPORT_JOBS_FOR_CONNECTION_RESULT_V1='messaging.DeleteHistoryImportJobsForConnectionResult.v1' as const
export const PATCH_HISTORY_IMPORT_JOB_COMMAND_V1='messaging.PatchHistoryImportJobCommand.v1' as const
export const PATCH_HISTORY_IMPORT_JOB_RESULT_V1='messaging.PatchHistoryImportJobResult.v1' as const
export const HISTORY_IMPORT_STATUSES_V1=['queued','running','completed','partial','failed']as const;export type HistoryImportStatusV1=typeof HISTORY_IMPORT_STATUSES_V1[number]
export interface DeleteHistoryImportJobCommandV1{contract:typeof DELETE_HISTORY_IMPORT_JOB_COMMAND_V1;jobId:string}
export interface DeleteHistoryImportJobResultV1{contract:typeof DELETE_HISTORY_IMPORT_JOB_RESULT_V1;deleted:true}
export interface UpdateHistoryImportJobCommandV1{contract:typeof UPDATE_HISTORY_IMPORT_JOB_COMMAND_V1;jobId:string;status:HistoryImportStatusV1;resultType:unknown;messagesImported:unknown;chatsScanned:unknown;contactsFound:unknown;startedAt:Date|null;finishedAt:Date|null;coveredPeriodFrom:Date|null;coveredPeriodTo:Date|null}
export interface UpdateHistoryImportJobResultV1{contract:typeof UPDATE_HISTORY_IMPORT_JOB_RESULT_V1;updated:true}
export type HistoryImportChannelV1='whatsapp'|'telegram'|'max'
export interface DeleteHistoryImportJobsForConnectionCommandV1{contract:typeof DELETE_HISTORY_IMPORT_JOBS_FOR_CONNECTION_COMMAND_V1;channel:HistoryImportChannelV1;connectionId:string}
export interface DeleteHistoryImportJobsForConnectionResultV1{contract:typeof DELETE_HISTORY_IMPORT_JOBS_FOR_CONNECTION_RESULT_V1;deleted:true}
export interface HistoryImportJobPatchV1{status?:string;resultType?:string;messagesImported?:number;chatsScanned?:number;contactsFound?:number;startedAt?:Date|null;finishedAt?:Date|null;coveredPeriodFrom?:Date|null;coveredPeriodTo?:Date|null;detailsJson?:unknown}
export interface PatchHistoryImportJobCommandV1{contract:typeof PATCH_HISTORY_IMPORT_JOB_COMMAND_V1;jobId:string;patch:HistoryImportJobPatchV1}
export interface PatchHistoryImportJobResultV1{contract:typeof PATCH_HISTORY_IMPORT_JOB_RESULT_V1;updated:boolean}
export class HistoryImportJobCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:HistoryImportJobCommandValidationError['code'],message:string){super(message);this.name='HistoryImportJobCommandValidationError';this.code=code}}
const STATUSES=new Set<string>(HISTORY_IMPORT_STATUSES_V1),isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);function invalid(m:string):never{throw new HistoryImportJobCommandValidationError('INVALID_CONTRACT',m)}function envelope(input:unknown,expected:string,prefix:string,fields:string[]):Record<string,unknown>{if(!isRecord(input))invalid('command must be an object');const extra=Object.keys(input).filter(k=>!fields.includes(k));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new HistoryImportJobCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}function dateOrNull(v:unknown,key:string):asserts v is Date|null{if(v!==null&&!(v instanceof Date))invalid(`${key} must be a Date or null`)}
export function parseDeleteHistoryImportJobCommandV1(input:unknown):DeleteHistoryImportJobCommandV1{const v=envelope(input,DELETE_HISTORY_IMPORT_JOB_COMMAND_V1,'messaging.DeleteHistoryImportJobCommand.',['contract','jobId']);if(typeof v.jobId!=='string')invalid('jobId must be a string');return v as unknown as DeleteHistoryImportJobCommandV1}
export function parseUpdateHistoryImportJobCommandV1(input:unknown):UpdateHistoryImportJobCommandV1{const fields=['contract','jobId','status','resultType','messagesImported','chatsScanned','contactsFound','startedAt','finishedAt','coveredPeriodFrom','coveredPeriodTo'],v=envelope(input,UPDATE_HISTORY_IMPORT_JOB_COMMAND_V1,'messaging.UpdateHistoryImportJobCommand.',fields);if(typeof v.jobId!=='string')invalid('jobId must be a string');if(typeof v.status!=='string'||!STATUSES.has(v.status))invalid('status is invalid');for(const key of['resultType','messagesImported','chatsScanned','contactsFound'])if(!(key in v))invalid(`${key} is required`);for(const key of['startedAt','finishedAt','coveredPeriodFrom','coveredPeriodTo'])dateOrNull(v[key],key);return v as unknown as UpdateHistoryImportJobCommandV1}
export function parseDeleteHistoryImportJobsForConnectionCommandV1(input:unknown):DeleteHistoryImportJobsForConnectionCommandV1{const v=envelope(input,DELETE_HISTORY_IMPORT_JOBS_FOR_CONNECTION_COMMAND_V1,'messaging.DeleteHistoryImportJobsForConnectionCommand.',['contract','channel','connectionId']);if(v.channel!=='whatsapp'&&v.channel!=='telegram'&&v.channel!=='max')invalid('channel is invalid');if(typeof v.connectionId!=='string')invalid('connectionId must be a string');return v as unknown as DeleteHistoryImportJobsForConnectionCommandV1}
export function parsePatchHistoryImportJobCommandV1(input:unknown):PatchHistoryImportJobCommandV1{const v=envelope(input,PATCH_HISTORY_IMPORT_JOB_COMMAND_V1,'messaging.PatchHistoryImportJobCommand.',['contract','jobId','patch']);if(typeof v.jobId!=='string')invalid('jobId must be a string');if(!isRecord(v.patch))invalid('patch must be an object');const allowed=['status','resultType','messagesImported','chatsScanned','contactsFound','startedAt','finishedAt','coveredPeriodFrom','coveredPeriodTo','detailsJson'],extra=Object.keys(v.patch).filter(k=>!allowed.includes(k));if(extra.length)invalid(`unsupported patch field(s): ${extra.sort().join(', ')}`);if(v.patch.status!==undefined&&typeof v.patch.status!=='string')invalid('status must be a string');if(v.patch.resultType!==undefined&&typeof v.patch.resultType!=='string')invalid('resultType must be a string');for(const key of['messagesImported','chatsScanned','contactsFound'])if(v.patch[key]!==undefined&&typeof v.patch[key]!=='number')invalid(`${key} must be a number`);for(const key of['startedAt','finishedAt','coveredPeriodFrom','coveredPeriodTo'])if(v.patch[key]!==undefined)dateOrNull(v.patch[key],key);return v as unknown as PatchHistoryImportJobCommandV1}
