export const ENSURE_LEAD_CONVERSATION_COMMAND_V1='messaging.EnsureLeadConversationCommand.v1' as const
export const ENSURE_LEAD_CONVERSATION_RESULT_V1='messaging.EnsureLeadConversationResult.v1' as const
export const RESOLVE_CONVERSATION_COMMAND_V1='messaging.ResolveConversationCommand.v1' as const
export const RESOLVE_CONVERSATION_RESULT_V1='messaging.ResolveConversationResult.v1' as const
export type LeadConversationChannelV1='avito'|'whatsapp'|'telegram'|'phone'
export interface EnsureLeadConversationCommandV1{contract:typeof ENSURE_LEAD_CONVERSATION_COMMAND_V1;contactId:string;contactIdentityId:string;channel:LeadConversationChannelV1;providerAccountId:string;externalChatId:string;name:string|null;receivedAt:Date;metadata:Record<string,unknown>}
export interface EnsureLeadConversationResultV1{contract:typeof ENSURE_LEAD_CONVERSATION_RESULT_V1;chatId:string}
export interface ResolveConversationCommandV1{contract:typeof RESOLVE_CONVERSATION_COMMAND_V1;chatId:string}
export interface ResolveConversationResultV1{contract:typeof RESOLVE_CONVERSATION_RESULT_V1;resolved:true}
export class LeadConversationCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:LeadConversationCommandValidationError['code'],message:string){super(message);this.name='LeadConversationCommandValidationError';this.code=code}}
const CHANNELS=new Set(['avito','whatsapp','telegram','phone']),isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);function invalid(m:string):never{throw new LeadConversationCommandValidationError('INVALID_CONTRACT',m)}function envelope(input:unknown,expected:string,prefix:string,fields:string[]):Record<string,unknown>{if(!isRecord(input))invalid('command must be an object');const extra=Object.keys(input).filter(k=>!fields.includes(k));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new LeadConversationCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}function requiredString(v:unknown,key:string){if(typeof v!=='string'||v.trim()==='')invalid(`${key} is required`)}
export function parseEnsureLeadConversationCommandV1(input:unknown):EnsureLeadConversationCommandV1{const v=envelope(input,ENSURE_LEAD_CONVERSATION_COMMAND_V1,'messaging.EnsureLeadConversationCommand.',['contract','contactId','contactIdentityId','channel','providerAccountId','externalChatId','name','receivedAt','metadata']);for(const key of['contactId','contactIdentityId','providerAccountId','externalChatId'])requiredString(v[key],key);if(v.providerAccountId==='legacy'||v.providerAccountId!==String(v.providerAccountId).trim())invalid('providerAccountId must identify a concrete provider account');if(typeof v.channel!=='string'||!CHANNELS.has(v.channel))invalid('channel is invalid');if(v.name!==null&&typeof v.name!=='string')invalid('name must be a string or null');if(!(v.receivedAt instanceof Date))invalid('receivedAt must be a Date');if(!isRecord(v.metadata))invalid('metadata must be an object');return v as unknown as EnsureLeadConversationCommandV1}
export function parseResolveConversationCommandV1(input:unknown):ResolveConversationCommandV1{const v=envelope(input,RESOLVE_CONVERSATION_COMMAND_V1,'messaging.ResolveConversationCommand.',['contract','chatId']);requiredString(v.chatId,'chatId');return v as unknown as ResolveConversationCommandV1}
