export const SYNC_CALL_TIMELINE_COMMAND_V1='messaging.SyncCallTimelineCommand.v1' as const
export const SYNC_CALL_TIMELINE_RESULT_V1='messaging.SyncCallTimelineResult.v1' as const
export type CallTimelineDirectionV1='inbound'|'outbound'
export interface SyncCallTimelineCommandV1{contract:typeof SYNC_CALL_TIMELINE_COMMAND_V1;externalChatId:string;contactId:string;driverId:string|null;peer:string;callId:string;direction:CallTimelineDirectionV1;callStatus:string;durationSec:number|null;content:string;disposition:string;startedAt:Date;endedAt:Date|null}
export interface CallTimelineMessageV1{id:string;chatId:string;channel:'phone';type:'call';direction:CallTimelineDirectionV1;content:string;sentAt:Date;metadata:Record<string,unknown>|null}
export type SyncCallTimelineResultV1={contract:typeof SYNC_CALL_TIMELINE_RESULT_V1;action:'unchanged';chatId:string}|{contract:typeof SYNC_CALL_TIMELINE_RESULT_V1;action:'updated'|'created';chatId:string;message:CallTimelineMessageV1}
export class SyncCallTimelineCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:SyncCallTimelineCommandValidationError['code'],message:string){super(message);this.name='SyncCallTimelineCommandValidationError';this.code=code}}
const isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);function invalid(m:string):never{throw new SyncCallTimelineCommandValidationError('INVALID_CONTRACT',m)}function date(v:unknown,key:string,nullable=false){if((nullable&&v===null)||v instanceof Date)return;invalid(`${key} must be a Date${nullable?' or null':''}`)}
export function parseSyncCallTimelineCommandV1(input:unknown):SyncCallTimelineCommandV1{if(!isRecord(input))invalid('command must be an object');const fields=['contract','externalChatId','contactId','driverId','peer','callId','direction','callStatus','durationSec','content','disposition','startedAt','endedAt'],extra=Object.keys(input).filter(k=>!fields.includes(k));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==SYNC_CALL_TIMELINE_COMMAND_V1){if(typeof input.contract==='string'&&input.contract.startsWith('messaging.SyncCallTimelineCommand.'))throw new SyncCallTimelineCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${SYNC_CALL_TIMELINE_COMMAND_V1}`)}for(const key of['externalChatId','contactId','peer','callId','callStatus','content','disposition'])if(typeof input[key]!=='string')invalid(`${key} must be a string`);if(input.driverId!==null&&typeof input.driverId!=='string')invalid('driverId must be a string or null');if(input.direction!=='inbound'&&input.direction!=='outbound')invalid('direction is invalid');if(input.durationSec!==null&&typeof input.durationSec!=='number')invalid('durationSec must be a number or null');date(input.startedAt,'startedAt');date(input.endedAt,'endedAt',true);return input as unknown as SyncCallTimelineCommandV1}
