export const DELETE_API_LOGS_COMMAND_V1='fleet_operations.DeleteApiLogsCommand.v1' as const
export const DELETE_API_LOGS_RESULT_V1='fleet_operations.DeleteApiLogsResult.v1' as const
export const RECORD_API_LOG_COMMAND_V1='fleet_operations.RecordApiLogCommand.v1' as const
export const RECORD_API_LOG_RESULT_V1='fleet_operations.RecordApiLogResult.v1' as const
export interface DeleteApiLogsCommandV1{contract:typeof DELETE_API_LOGS_COMMAND_V1;connectionId:string}
export interface DeleteApiLogsResultV1{contract:typeof DELETE_API_LOGS_RESULT_V1;deletedCount:number}
export interface ApiLogDataV1{connectionId:string;method:string;requestUrl:string;requestBody:string|null;responseBody:string|null;statusCode:number;error:string|null;durationMs:number}
export interface ApiLogRecordV1 extends ApiLogDataV1{id:string;createdAt:Date}
export interface RecordApiLogCommandV1{contract:typeof RECORD_API_LOG_COMMAND_V1;data:ApiLogDataV1}
export interface RecordApiLogResultV1{contract:typeof RECORD_API_LOG_RESULT_V1;log:ApiLogRecordV1}
export class ApiLogCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:ApiLogCommandValidationError['code'],message:string){super(message);this.name='ApiLogCommandValidationError';this.code=code}}
const isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v),nonEmpty=(v:unknown):v is string=>typeof v==='string'&&v.trim()!=='',nullableString=(v:unknown):v is string|null=>v===null||typeof v==='string';function invalid(m:string):never{throw new ApiLogCommandValidationError('INVALID_CONTRACT',m)}function contract(input:Record<string,unknown>,expected:string,prefix:string){if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new ApiLogCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}}function fields(input:Record<string,unknown>,allowed:Set<string>){const extra=Object.keys(input).filter(k=>!allowed.has(k));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`)}
export function parseDeleteApiLogsCommandV1(input:unknown):DeleteApiLogsCommandV1{if(!isRecord(input))invalid('command must be an object');fields(input,new Set(['contract','connectionId']));contract(input,DELETE_API_LOGS_COMMAND_V1,'fleet_operations.DeleteApiLogsCommand.');if(!nonEmpty(input.connectionId))invalid('connectionId is required');return input as unknown as DeleteApiLogsCommandV1}
export function parseRecordApiLogCommandV1(input:unknown):RecordApiLogCommandV1{if(!isRecord(input))invalid('command must be an object');fields(input,new Set(['contract','data']));contract(input,RECORD_API_LOG_COMMAND_V1,'fleet_operations.RecordApiLogCommand.');if(!isRecord(input.data))invalid('data must be an object');fields(input.data,new Set(['connectionId','method','requestUrl','requestBody','responseBody','statusCode','error','durationMs']));for(const key of['connectionId','method','requestUrl'])if(!nonEmpty(input.data[key]))invalid(`${key} is required`);for(const key of['requestBody','responseBody','error'])if(!nullableString(input.data[key]))invalid(`${key} must be a string or null`);for(const key of['statusCode','durationMs'])if(typeof input.data[key]!=='number'||!Number.isInteger(input.data[key])||input.data[key]<0)invalid(`${key} must be a non-negative integer`);return input as unknown as RecordApiLogCommandV1}
