export const CREATE_API_CONNECTION_COMMAND_V1='fleet_operations.CreateApiConnectionCommand.v1' as const
export const CREATE_API_CONNECTION_RESULT_V1='fleet_operations.CreateApiConnectionResult.v1' as const
export const UPDATE_API_CONNECTION_NAME_COMMAND_V1='fleet_operations.UpdateApiConnectionNameCommand.v1' as const
export const UPDATE_API_CONNECTION_NAME_RESULT_V1='fleet_operations.UpdateApiConnectionNameResult.v1' as const
export const DELETE_API_CONNECTION_COMMAND_V1='fleet_operations.DeleteApiConnectionCommand.v1' as const
export const DELETE_API_CONNECTION_RESULT_V1='fleet_operations.DeleteApiConnectionResult.v1' as const
export interface CreateApiConnectionCommandV1{contract:typeof CREATE_API_CONNECTION_COMMAND_V1;clid:string;apiKey:string;parkId:string;name:string|null}
export interface CreateApiConnectionResultV1{contract:typeof CREATE_API_CONNECTION_RESULT_V1;created:true}
export interface UpdateApiConnectionNameCommandV1{contract:typeof UPDATE_API_CONNECTION_NAME_COMMAND_V1;connectionId:string;name:string|null}
export interface UpdateApiConnectionNameResultV1{contract:typeof UPDATE_API_CONNECTION_NAME_RESULT_V1;updated:true}
export interface DeleteApiConnectionCommandV1{contract:typeof DELETE_API_CONNECTION_COMMAND_V1;connectionId:string}
export interface DeleteApiConnectionResultV1{contract:typeof DELETE_API_CONNECTION_RESULT_V1;deleted:true}
export class ApiConnectionCommandValidationError extends Error{readonly code:'INVALID_CONTRACT'|'UNSUPPORTED_CONTRACT_VERSION';constructor(code:ApiConnectionCommandValidationError['code'],message:string){super(message);this.name='ApiConnectionCommandValidationError';this.code=code}}
const isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);function invalid(m:string):never{throw new ApiConnectionCommandValidationError('INVALID_CONTRACT',m)}function envelope(input:unknown,expected:string,prefix:string,fields:string[]):Record<string,unknown>{if(!isRecord(input))invalid('command must be an object');const extra=Object.keys(input).filter(k=>!fields.includes(k));if(extra.length)invalid(`unsupported field(s): ${extra.sort().join(', ')}`);if(input.contract!==expected){if(typeof input.contract==='string'&&input.contract.startsWith(prefix))throw new ApiConnectionCommandValidationError('UNSUPPORTED_CONTRACT_VERSION',`unsupported contract version: ${input.contract}`);invalid(`contract must equal ${expected}`)}return input}function string(v:unknown,key:string){if(typeof v!=='string')invalid(`${key} must be a string`)}function nullableString(v:unknown,key:string){if(v!==null&&typeof v!=='string')invalid(`${key} must be a string or null`)}
export function parseCreateApiConnectionCommandV1(input:unknown):CreateApiConnectionCommandV1{const v=envelope(input,CREATE_API_CONNECTION_COMMAND_V1,'fleet_operations.CreateApiConnectionCommand.',['contract','clid','apiKey','parkId','name']);string(v.clid,'clid');string(v.apiKey,'apiKey');string(v.parkId,'parkId');nullableString(v.name,'name');return v as unknown as CreateApiConnectionCommandV1}
export function parseUpdateApiConnectionNameCommandV1(input:unknown):UpdateApiConnectionNameCommandV1{const v=envelope(input,UPDATE_API_CONNECTION_NAME_COMMAND_V1,'fleet_operations.UpdateApiConnectionNameCommand.',['contract','connectionId','name']);string(v.connectionId,'connectionId');nullableString(v.name,'name');return v as unknown as UpdateApiConnectionNameCommandV1}
export function parseDeleteApiConnectionCommandV1(input:unknown):DeleteApiConnectionCommandV1{const v=envelope(input,DELETE_API_CONNECTION_COMMAND_V1,'fleet_operations.DeleteApiConnectionCommand.',['contract','connectionId']);string(v.connectionId,'connectionId');return v as unknown as DeleteApiConnectionCommandV1}
