export const MAX_DISPATCH_LEDGER_ENABLED = 'MAX_DISPATCH_LEDGER_ENABLED'
export const MAX_DISPATCH_PAGE_LIMIT = 200
export const MAX_RECONCILIATION_PAGE_LIMIT = 200
export const DEFAULT_ATTEMPT_CLAIM_MILLISECONDS = 30_000
export const MAX_DISPATCH_CONCURRENCY_RETRIES = 16
export const DISPATCH_EVIDENCE_VERSION = 'max-dispatch-evidence-v1'
